### ISSUE TITLE
typo: "pesudo" in function name and code comment

### ISSUE THREAD

**Issue by tan90xx** [chaufanglin/Normal2Whisper#2]
I noticed a typo in the function name and the accompanying code comment for the whisper generation function. The term "pesudo" should be corrected to "pseudo".  
Affected .py documentations:  
https://github.com/chaufanglin/Normal2Whisper/blob/eb887b2228172d5316fc33d4c0dc88421b651803/utils.py#L222
https://github.com/chaufanglin/Normal2Whisper/blob/eb887b2228172d5316fc33d4c0dc88421b651803/data_gen.py#L6
Proposed Changes:  Change the function name to def `pseudo_whisper_gen`. 
Thank you!

**Comment by chaufanglin** [comment]
Hi,
Thanks for letting me know! I just fixed the typo. 

Many thanks,
Zhaofeng

**Comment by tan90xx** [comment]
Thanks for taking the time. Looks great!
